DELETE https://crudcrud.com/api/a49a929b43a34adea37ab5611e453404/student/670c34f2a0a8cd03e818a743
Accept: application/json

###
GET https://crudcrud.com/api/a49a929b43a34adea37ab5611e453404/student/670c34f2a0a8cd03e818a743
Accept: application/json

###
POST  https://crudcrud.com/api/a49a929b43a34adea37ab5611e453404/student
Content-Type: application/json

{
  "name" : "Вася Пупкин",
  "grade" : 2
}

